name: Deploy Project
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run linter
              run: npm run lint
            - name: Linter run completed
              run: echo "Linter run completed"
    
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps: 
            - name: Get code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Tests run completed
              run: echo "Tests run completed"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Build completed
              run: echo "Build completed"